package ui;

import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import main.Main;

public class JPanelSplash extends JPanel implements ActionListener 
{
	// A unique ID required because this class is serializable
	// This can be auto generated by hovering over the warning on the class name
	private static final long serialVersionUID = 4713004725086983815L;

	private final String ACTION_SPLASH = "SPLASH";

	JFrameATM atmFrame;
	
	JLabel lblTitle;
	JLabel lblSpace1;
	JLabel lblContributors;
	JLabel lblContributors1;
	JLabel lblContributors2;
	JLabel lblContributors3;
	JLabel lblSpace2;
	JLabel lblCopyright;
	JButton btnPrint;
	
	/**
	 * Constructor for the Splash panel
	 * 
	 * @param appFrame Parent frame that will hold the panels created by actions performed by this class
	 */
	public JPanelSplash(JFrameATM atmFrame) {
		
		// Save the application frame
		this.atmFrame = atmFrame;
		
		// Set the panel size to match the global parameters
		this.setSize(Main.ATM_PANEL_WIDTH, Main.ATM_PANEL_HEIGHT);
		
		// Set layout and initial constraints
		this.setLayout(new GridBagLayout());
		GridBagConstraints constraints = new GridBagConstraints();
		constraints.insets = new Insets(5,5,5,5);
		
		// Create and add components for this panel
		
		lblTitle = new JLabel("TaKeBo Bank ATM System ");
		lblTitle.setFont(new Font("Matura MT Script Capitals", Font.ITALIC | Font.BOLD, 28));
		constraints.gridx = 0;
		constraints.gridy = 0;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblTitle, constraints);
		
		lblSpace1 = new JLabel(" ");
		lblSpace1.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 0;
		constraints.gridy = 1;
		constraints.gridwidth = 2;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblSpace1, constraints);
		
		lblContributors = new JLabel("Contributors: ");
		lblContributors.setFont(new Font("Tahoma", Font.PLAIN, 20));
		constraints.gridx = 0;
		constraints.gridy = 2;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblContributors, constraints);
		
		lblContributors1 = new JLabel("(Ta) - Tamara Jennings ");
		lblContributors1.setFont(new Font("Tahoma", Font.PLAIN, 20));
		constraints.gridx = 0;
		constraints.gridy = 3;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblContributors1, constraints);
		
		lblContributors2 = new JLabel("(Ke) - Kelly Fox ");
		lblContributors2.setFont(new Font("Tahoma", Font.PLAIN, 20));
		constraints.gridx = 0;
		constraints.gridy = 4;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblContributors2, constraints);
		
		lblContributors3 = new JLabel("(Bo) - Bob Elward ");
		lblContributors3.setFont(new Font("Tahoma", Font.PLAIN, 20));
		constraints.gridx = 0;
		constraints.gridy = 5;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblContributors3, constraints);
		
		lblSpace2 = new JLabel(" ");
		lblSpace2.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 0;
		constraints.gridy = 6;
		constraints.gridwidth = 2;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblSpace2, constraints);
		
		lblCopyright = new JLabel("Copyright (c) 2020 - TaKeBo Bank, LLC ");
		lblCopyright.setFont(new Font("Tahoma", Font.PLAIN, 12));
		constraints.gridx = 0;
		constraints.gridy = 7;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblCopyright, constraints);

		// All done
		return;
	}
	
	public void showPanel() {
		
		// Set this panel as the frame's content panel and update the frame title
		atmFrame.setContentPanel(this);
		atmFrame.setTitle(Main.ATM_FRAME_TITLE + " - (" + this.getClass().getSimpleName() + ")");
		
		// Re-paint and re-validate to display the panel
		atmFrame.repaint();
		atmFrame.revalidate();

		// All done
		return;
	}
	
	/**
	 * Handles the actions that are requested by this panel
	 * 
	 * @param actionEvent An ActionEvent containing the details of the event
	 */
	@Override
	public void actionPerformed(ActionEvent actionEvent) {

		String action = actionEvent.getActionCommand();
		
		if(Main.DEBUG)
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": Got action: : " + action
			          );
		
		switch (action) {
		
			case ACTION_SPLASH:
				// This never gets requested				
				
				break;
		}
		
		// All done
		return;
	}
	
}
