package ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

import main.Main;
import model.Machine;

public class JPanelTechnician extends JPanel implements ActionListener
{
	// A unique ID required because this class is serializable
	// This can be auto generated by hovering over the warning on the class name
	private static final long serialVersionUID = -3640709993364842489L;

	private final String ACTION_RESET_CASH = "RESET_CASH";
	private final String ACTION_RESET_DEPOSIT = "RESET_DEPOSIT";
	private final String ACTION_RESET_PAPER = "RESET_PAPER";
	private final String ACTION_PRINT = "PRINT";
	private final String ACTION_DONE = "DONE";

	JFrameATM atmFrame;
	
	JLabel lblWelcome;
	JLabel lblMessage;
	JLabel lblCashLevel;
	JLabel lblCashLevelStatus;
	JLabel lblDepositLevel;
	JLabel lblDepositLevelStatus;
	JLabel lblPrinterPaperLevel;
	JLabel lblPrinterPaperLevelStatus;
	JLabel lblPrint;
	JLabel lblDone;
	
	/**
	 * Constructor for the panel
	 * 
	 * @param appFrame Parent frame that will hold the panels created by actions performed by this class
	 */
	public JPanelTechnician(JFrameATM atmFrame) {
		
		// Save the application frame
		this.atmFrame = atmFrame;
		
		// Reset the frame's button action listeners
		atmFrame.setButtonActionDefaults();
		
		// Set frame background color
		this.setBackground(Main.ATM_CONTENT_PANEL_BACKGROUND);

        // Number of rows and heights
		int panelRows = 7;
        int[] rows = new int[panelRows];
        Arrays.fill(rows, (Main.ATM_PANEL_HEIGHT / panelRows));
		
		// Number of columns and widths
        int panelColumns = 3;
        int[] columns = new int[panelColumns];
        Arrays.fill(columns, (Main.ATM_PANEL_WIDTH / panelColumns));
		
		// Set layout
		GridBagLayout gridBagLayout = new GridBagLayout();
        gridBagLayout.rowHeights = rows;
        gridBagLayout.columnWidths = columns;
		this.setLayout(gridBagLayout);
		
		// Set initial constraints
		GridBagConstraints constraints = new GridBagConstraints();
		constraints.insets = new Insets(0,0,0,0);
		
		// Create and add components for this panel
		
		lblWelcome = new JLabel("Service Status. ");
		lblWelcome.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 0;
		constraints.gridy = 1;
		constraints.gridwidth = 3;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblWelcome, constraints);
		
		lblMessage = new JLabel(" ");
		lblMessage.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblMessage.setForeground(Color.RED);
		constraints.gridx = 0;
		constraints.gridy = 2;
		constraints.gridwidth = 3;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.CENTER;
		this.add(lblMessage, constraints);
		
		lblCashLevel = new JLabel("Cash Level: ");
		lblCashLevel.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 0;
		constraints.gridy = 3;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		this.add(lblCashLevel, constraints);
		
		lblCashLevelStatus = new JLabel("Undefined ");
		lblCashLevelStatus.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 1;
		constraints.gridy = 3;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,10,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.WEST;
		this.add(lblCashLevelStatus, constraints);
		
		lblDepositLevel = new JLabel("Deposit Level: ");
		lblDepositLevel.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 0;
		constraints.gridy = 4;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		this.add(lblDepositLevel, constraints);
		
		lblDepositLevelStatus = new JLabel("Undefined ");
		lblDepositLevelStatus.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 1;
		constraints.gridy = 4;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,10,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.WEST;
		this.add(lblDepositLevelStatus, constraints);
		
		lblPrinterPaperLevel = new JLabel("Paper Level: ");
		lblPrinterPaperLevel.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 0;
		constraints.gridy = 5;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		this.add(lblPrinterPaperLevel, constraints);
		
		lblPrinterPaperLevelStatus = new JLabel("Undefined ");
		lblPrinterPaperLevelStatus.setFont(new Font("Tahoma", Font.BOLD, 22));
		constraints.gridx = 1;
		constraints.gridy = 5;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,10,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.WEST;
		this.add(lblPrinterPaperLevelStatus, constraints);
		
		int labelWidth = 185;
		int labelHeight = 40;
		
		lblDone = new JLabel("Reset ", JLabel.RIGHT);
		lblDone.setFont(new Font("Tahoma", Font.BOLD, 22));
		atmFrame.setActionListener_Right1(ACTION_RESET_CASH, this);
		constraints.gridx = 2;
		constraints.gridy = 3;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,10);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		lblDone.setOpaque(true);
		lblDone.setBackground(Color.BLACK);
		lblDone.setForeground(Color.WHITE);
		//lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLUE));
		lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, new Color(0x007FFF)));
		//lblDone.setBorder(new BevelBorder(BevelBorder.RAISED));
		lblDone.setMinimumSize(new Dimension(labelWidth, labelHeight)); // Width, Height
		lblDone.setPreferredSize(new Dimension(labelWidth, labelHeight));
		lblDone.setMaximumSize(new Dimension(labelWidth, labelHeight));
		this.add(lblDone, constraints);
		
		lblDone = new JLabel("Reset ", JLabel.RIGHT);
		lblDone.setFont(new Font("Tahoma", Font.BOLD, 22));
		atmFrame.setActionListener_Right2(ACTION_RESET_DEPOSIT, this);
		constraints.gridx = 2;
		constraints.gridy = 4;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,10);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		lblDone.setOpaque(true);
		lblDone.setBackground(Color.BLACK);
		lblDone.setForeground(Color.WHITE);
		//lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLUE));
		lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, new Color(0x007FFF)));
		//lblDone.setBorder(new BevelBorder(BevelBorder.RAISED));
		lblDone.setMinimumSize(new Dimension(labelWidth, labelHeight)); // Width, Height
		lblDone.setPreferredSize(new Dimension(labelWidth, labelHeight));
		lblDone.setMaximumSize(new Dimension(labelWidth, labelHeight));
		this.add(lblDone, constraints);
		
		lblDone = new JLabel("Reset ", JLabel.RIGHT);
		lblDone.setFont(new Font("Tahoma", Font.BOLD, 22));
		atmFrame.setActionListener_Right3(ACTION_RESET_PAPER, this);
		constraints.gridx = 2;
		constraints.gridy = 5;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,10);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		lblDone.setOpaque(true);
		lblDone.setBackground(Color.BLACK);
		lblDone.setForeground(Color.WHITE);
		//lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLUE));
		lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, new Color(0x007FFF)));
		//lblDone.setBorder(new BevelBorder(BevelBorder.RAISED));
		lblDone.setMinimumSize(new Dimension(labelWidth, labelHeight)); // Width, Height
		lblDone.setPreferredSize(new Dimension(labelWidth, labelHeight));
		lblDone.setMaximumSize(new Dimension(labelWidth, labelHeight));
		this.add(lblDone, constraints);
		
		lblPrint = new JLabel(" Print", JLabel.LEFT);
		lblPrint.setFont(new Font("Tahoma", Font.BOLD, 22));
		atmFrame.setActionListener_Left4(ACTION_PRINT, this);
		constraints.gridx = 0;
		constraints.gridy = 6;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,10,0,0);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.WEST;
		lblPrint.setOpaque(true);
		lblPrint.setBackground(Color.BLACK);
		lblPrint.setForeground(Color.WHITE);
		//lblPrint.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLUE));
		lblPrint.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, new Color(0x007FFF)));
		//lblPrint.setBorder(new BevelBorder(BevelBorder.RAISED));
		lblPrint.setMinimumSize(new Dimension(labelWidth, labelHeight)); // Width, Height
		lblPrint.setPreferredSize(new Dimension(labelWidth, labelHeight));
		lblPrint.setMaximumSize(new Dimension(labelWidth, labelHeight));
		this.add(lblPrint, constraints);
		
		lblDone = new JLabel("Done ", JLabel.RIGHT);
		lblDone.setFont(new Font("Tahoma", Font.BOLD, 22));
		atmFrame.setActionListener_Right4(ACTION_DONE, this);
		constraints.gridx = 2;
		constraints.gridy = 6;
		constraints.gridwidth = 1;
		constraints.gridheight = 1;
		constraints.insets = new Insets(0,0,0,10);  //top, left, bottom, right padding
		constraints.anchor = GridBagConstraints.EAST;
		lblDone.setOpaque(true);
		lblDone.setBackground(Color.BLACK);
		lblDone.setForeground(Color.WHITE);
		//lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLUE));
		lblDone.setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, new Color(0x007FFF)));
		//lblDone.setBorder(new BevelBorder(BevelBorder.RAISED));
		lblDone.setMinimumSize(new Dimension(labelWidth, labelHeight)); // Width, Height
		lblDone.setPreferredSize(new Dimension(labelWidth, labelHeight));
		lblDone.setMaximumSize(new Dimension(labelWidth, labelHeight));
		this.add(lblDone, constraints);
		
		/*
		// Set initial component focus
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				// Doesn't work when you just want to press the enter key and not click
				//boolean focused = btnDone.requestFocusInWindow();
				//if (Main.DEBUG)
			    //	System.err.println(this.getClass().getTypeName() + "."
				//	         + (new Throwable().getStackTrace()[0].getMethodName())
				//	         + ": focused: >" + focused + "<"
				//	          );
				
				// Use this when you just want to press the enter key and not have to click the button
				atmFrame.getRootPane().setDefaultButton( btnDone );
				if (Main.DEBUG)
			    	System.err.println(this.getClass().getTypeName() + "."
					         + (new Throwable().getStackTrace()[0].getMethodName())
					         + ": DefaultButton set >" + btnDone.getText() + "<"
					          );
			}
		});
		*/

		// All done
		return;
	}
	
	public void showPanel() {
		
		// Set this panel as the frame's content panel and update the frame title
		atmFrame.setContentPanel(this);
		atmFrame.setTitle(Main.ATM_FRAME_TITLE + " - (" + this.getClass().getSimpleName() + ")");
		
		// Actions prior to display
        
		// Default transaction type
		atmFrame.setTransactionType("TECHNICIAN");
		
		// Get the machine object to retrieve the statuses
		Machine machine = atmFrame.getMachine();
		
		// Set status values
		lblCashLevelStatus.setText(machine.getCashStatus());
		lblCashLevelStatus.setForeground(machine.getCashStatusColor());
		
		lblDepositLevelStatus.setText(machine.getDepositStatus());
		lblDepositLevelStatus.setForeground(machine.getDepositStatusColor());
		
		lblPrinterPaperLevelStatus.setText(machine.getPaperStatus());
		lblPrinterPaperLevelStatus.setForeground(machine.getPaperStatusColor());
		
		// Re-paint and re-validate to display the panel
		atmFrame.repaint();
		atmFrame.revalidate();

		// All done
		return;
	}
	
	/**
	 * Handles the actions that are requested by this panel
	 * 
	 * @param actionEvent An ActionEvent containing the details of the event
	 */
	@Override
	public void actionPerformed(ActionEvent actionEvent) {

		String action = actionEvent.getActionCommand();
		
		if(Main.DEBUG)
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": Got action: : " + action
			          );
		
		switch (action) {
			
			case ACTION_RESET_CASH:
			{
				// Reset the cash amount
				resetCashAmount();
				
				// Update the screen
				showPanel();
				
				break;
			}
			
			case ACTION_RESET_DEPOSIT:
			{
				// Reset the deposit fill percent
				resetDepositFillPercent();
				
				// Update the screen
				showPanel();
				
				break;
			}
			
			case ACTION_RESET_PAPER:
			{
				// Reset the paper length
				resetPaperLength();
				
				// Update the screen
				showPanel();
				
				break;
			}
			
			case ACTION_PRINT:
			{
				// Print receipt
				
				// Check paper level
				if (atmFrame.getMachine().getPaperLength() > 0)
				{
					// Create the print receipt pane and place it on the frame
					JPanelPrintReceipt panelPrintReceipt = new JPanelPrintReceipt(atmFrame);
					panelPrintReceipt.showPanel();
				}
				else
				{
					lblMessage.setText("Out of paper.");
				}

				break;
			}
			
			case ACTION_DONE:
			{
				// Create the logon panel and place it on the frame
				JPanelLogon panelLogon = new JPanelLogon(atmFrame);
				panelLogon.showPanel();
				
				break;
			}
		}
		
		// All done
		return;
	}
	
	private void resetCashAmount()
	{
		if(Main.DEBUG)
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": Here "
			          );
		
		// Reset the cash amount
		try
		{
			// Check that we've lost the connection
			if (!Main.atmFrame.dataAccess.isConnected())
			{
				// Attempt to reconnect
				Main.atmFrame.dataAccess.connect();
			}
			
			BigDecimal resetCashAmount = new BigDecimal(10000.00);
			ResultSet resultSet = Main.atmFrame.dataAccess.executeCallString("{call ResetMachineCash(?, ?)}", Machine.MACHINE_ID
					                                                                                        , resetCashAmount);
			// No result set is returned so need the null check first
			if(resultSet != null && resultSet.next())
			{
				try
				{
					// No result set is returned
				}
				catch (Exception ex)
				{
			    	System.err.println(this.getClass().getTypeName() + "."
					         + (new Throwable().getStackTrace()[0].getMethodName())
					         + ": Exception: \n" 
					         + ex.getMessage()
					          );
				}
			}
		}
		catch (SQLException sqlEx)
		{
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": SQLException: \n" 
			         + sqlEx.getMessage()
			          );
		}
		
		// Get the machine object to retrieve the statuses
		Machine machine = Machine.getInstance();
		machine.getCurrentMachineStatus();
		
		// All done
		return;
	}
	
	private void resetDepositFillPercent()
	{
		if(Main.DEBUG)
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": Here "
			          );
		
		// Reset the deposit fill percent
		try
		{
			// Check that we've lost the connection
			if (!Main.atmFrame.dataAccess.isConnected())
			{
				// Attempt to reconnect
				Main.atmFrame.dataAccess.connect();
			}
			
			int resetDepositFillPercent = 0;
			ResultSet resultSet = Main.atmFrame.dataAccess.executeCallString("{call ResetMachineDeposit(?, ?)}", Machine.MACHINE_ID
					                                                                                           , resetDepositFillPercent);
			// No result set is returned so need the null check first
			if(resultSet != null && resultSet.next())
			{
				try
				{
					// No result set is returned
				}
				catch (Exception ex)
				{
			    	System.err.println(this.getClass().getTypeName() + "."
					         + (new Throwable().getStackTrace()[0].getMethodName())
					         + ": Exception: \n" 
					         + ex.getMessage()
					          );
				}
			}
		}
		catch (SQLException sqlEx)
		{
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": SQLException: \n" 
			         + sqlEx.getMessage()
			          );
		}
		
		// Get the machine object to retrieve the statuses
		Machine machine = Machine.getInstance();
		machine.getCurrentMachineStatus();
		
		// All done
		return;
	}
	
	private void resetPaperLength()
	{
		if(Main.DEBUG)
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": Here "
			          );
		
		// Reset the paper length
		try
		{
			// Check that we've lost the connection
			if (!Main.atmFrame.dataAccess.isConnected())
			{
				// Attempt to reconnect
				Main.atmFrame.dataAccess.connect();
			}
			
			int resetPaperlength = 100;
			ResultSet resultSet = Main.atmFrame.dataAccess.executeCallString("{call ResetMachinePaper(?, ?)}", Machine.MACHINE_ID
					                                                                                         , resetPaperlength);
			// No result set is returned so need the null check first
			if(resultSet != null && resultSet.next())
			{
				try
				{
					// No result set is returned
				}
				catch (Exception ex)
				{
			    	System.err.println(this.getClass().getTypeName() + "."
					         + (new Throwable().getStackTrace()[0].getMethodName())
					         + ": Exception: \n" 
					         + ex.getMessage()
					          );
				}
			}
		}
		catch (SQLException sqlEx)
		{
	    	System.err.println(this.getClass().getTypeName() + "."
			         + (new Throwable().getStackTrace()[0].getMethodName())
			         + ": SQLException: \n" 
			         + sqlEx.getMessage()
			          );
		}
			
		// Get the machine object to retrieve the statuses
		Machine machine = Machine.getInstance();
		machine.getCurrentMachineStatus();
		
		// All done
		return;
	}

}
